name: Java CI/CD with AWS S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean install

    - name: Upload artifact to S3
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1  # Replace with your AWS region
    - run: aws s3 cp target/devops-demo-1.0-SNAPSHOT.jar s3://pantelis-devops-demo-bucket/devops-demo.jar
    
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
        application_name: pantelapp
        environment_name: Pantelapp-env
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: target/devops-demo-1.0-SNAPSHOT.jar
        existing_bucket_name: pantelis-devops-demo-bucket
        s3_key: devops-demo.jar